// <auto-generated />
namespace WebsiteBanGiay.IdentityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init));
        
        string IMigrationMetadata.Id
        {
            get { return "202212240640317_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
